name: use aws-nuke to remove everything in AWS

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: aws-nuke dry run
      uses: "docker://quay.io/rebuy/aws-nuke:v2.15.0"
      with:
        args: |
          --config .github/aws-nuke.yaml
          --force
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
