name: aws eks terraform verification

on:
  push:
    paths:
      - ".github/actions/verify/action.yml"
      - ".github/workflows/aws-eks-verify.yml"
      - "aws/eks/eks-terraform-scripts/**"
      - "!**.md"
  pull_request:
    paths:
      - ".github/actions/verify/action.yml"
      - ".github/workflows/aws-eks-verify.yml"
      - "aws/eks/eks-terraform-scripts/**"
      - "!**.md"
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws/eks/eks-terraform-scripts/
    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      TF_CLI_ARGS: "-no-color"
      TF_GLOBAL_ARGS: "-chdir=aws/eks/eks-terraform-scripts/"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - uses: ./.github/actions/verify

  apply:
    runs-on: ubuntu-latest
    needs: verify
    defaults:
      run:
        working-directory: aws/eks/eks-terraform-scripts/
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      TF_CLI_ARGS: "-no-color"
      TF_GLOBAL_ARGS: "-chdir=aws/eks/eks-terraform-scripts/"
    steps:
      - uses: actions/checkout@v2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Make sure we have destroyed any leftover resources from previous runs
        if: always()
        uses: ./.github/actions/nuke

      #- uses: ./.github/actions/apply

      # TODO: Run EKS specific jobs/steps here.

      #- name: Terraform Destroy
      #  if: always()
      #  uses: ./.github/actions/destroy
